### ISSUE TITLE
TypeError: PythonShell.run is not a function

### ISSUE THREAD

**Issue by sni-J** [extrabacon/python-shell#148]
Today, my node modules have been reset for somewhat reason(idk) and I re-installed it. It worked properly until yesterday, but this error suddenly occurred.
+) I'm using ExpressJS

Error Message
```
TypeError: PythonShell.run is not a function
    at getKeyword (/home/joon/Desktop/server_study/db.js:313:17)
```

db.js
```
const PythonShell = require('python-shell');

var pyOptions = {
    mode: 'text',
    pythonPath: '/usr/bin/python3.5',
    pythonOptions: ['-u'],
    scriptPath: './python',
    args: ['title', 'researcher', 'path_of_txt']
};

...

function pythonTest(cb){
    PythonShell.run("x=1;print(x)", null, (err, results)=>{
        console.log(results);
    });
}
```

package.json
```
{
  "name": "server_study",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "body-parser": "^1.18.3",
    "curl": "^0.1.4",
    "ejs": "^2.6.1",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
    "i18n": "^0.8.3",
    "jquery": "^3.3.1",
    "jsdom": "^11.10.0",
    "multer": "^1.3.0",
    "mysql": "^2.16.0",
    "nodemailer": "^4.6.8",
    "pdf2json": "^1.1.7",
    "python-shell": "^1.0.3",
    "serve-index": "^1.9.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "private": true
}
```

**Comment by Almenon** [comment]
You're using require. If you switch to import it should work

On Sep 6, 2018 1:41 AM, "sni-J" <notifications@github.com> wrote:

Today, my node modules have been reset for somewhat reason(idk) and I
re-installed it. It worked properly until yesterday, but this error
suddenly occurred.

Error Message

TypeError: PythonShell.run is not a function
    at getKeyword (/home/joon/바탕화면/server_study/db.js:313:17)

db.js

const PythonShell = require('python-shell');

var pyOptions = {
    mode: 'text',
    pythonPath: '/usr/bin/python3.5',
    pythonOptions: ['-u'],
    scriptPath: './python',
    args: ['title', 'researcher', 'path_of_txt']
};

...

function pythonTest(cb){
    PythonShell.run("x=1;print(x)", null, (err, results)=>{
        console.log(results);
    });
}

package.json

{
  "name": "server_study",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "body-parser": "^1.18.3",
    "curl": "^0.1.4",
    "ejs": "^2.6.1",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
    "i18n": "^0.8.3",
    "jquery": "^3.3.1",
    "jsdom": "^11.10.0",
    "multer": "^1.3.0",
    "mysql": "^2.16.0",
    "nodemailer": "^4.6.8",
    "pdf2json": "^1.1.7",
    "python-shell": "^1.0.3",
    "serve-index": "^1.9.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "private": true
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/extrabacon/python-shell/issues/148>, or mute the thread

**Comment by sni-J** [comment]
I'm using ExpressJS...

**Comment by Almenon** [comment]
I Looked it up and apparently it's not that simple. Imports are a es6 feature so I thought they would work in node, given that even the outdated node 6.14.4 [supports the vast majority of es6 features](https://node.green/).  But apparently only the latest edition of node supports imports.  

See https://stackoverflow.com/questions/45854169/how-can-i-use-an-es6-import-in-node

So if you want to use imports you have four options:
1) Use latest version of node with --experimental-modules flag. Node 8.5 might also work.
2) use [babel](https://timonweb.com/posts/how-to-enable-es6-imports-in-nodejs/)
3) use [esm](https://www.npmjs.com/package/esm)
4) use typescript (highly reccomend this)

And if none of those work for you, you can use python-shell 0.5.0 which uses require.

**Comment by sni-J** [comment]
Thanks for your help!
