### ISSUE TITLE
childProcess pid is not the same pid as python pid

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#236]
**Describe the bug**
childProcess under `PythonShell.childProcess.pid` is not the same pid as python  `os.getpid()` pid

**Python code**

```python
import sys
import os

class Unbuffered(object):
    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def writelines(self, datas):
        self.stream.writelines(datas)
        self.stream.flush()

    def __getattr__(self, attr):
        return getattr(self.stream, attr)

sys.stdout = Unbuffered(sys.stdout)
print(f'python pid: {os.getpid()}')
```

**Javascript code**
```javascript
const options = { scriptPath: 'C:\\users\\leona\\iq\\iq-websocket\\python\\botR'};
const pyTeste = new PythonShell('teste.py', options);
pyTeste
  .on('message', (line: string) => {
    console.log(line);
  })
  .on('stderr', (std: string) => {
    console.log(std);
  })
  .on('error', err => {
    console.log('err');
    console.log(err);
  })
  .on('close', () => {
    console.log('Programa finalizado');
  });

console.log(`child process pid: ${pyTeste.childProcess.pid}`);
```

**Expected behavior**
Both `pids` should be the same

**Actual behavior**
output:
```
child process pid: 52188
python pid: 40884
```

**Other Information (please complete the following information):**
 - OS: Windows10
 - Python Version: 3.8.7
 - Node Version: 12.15.0

**Comment by Almenon** [comment]
This is because the `py` launcher launches python as a subprocess. To launch python directly you can set `pythonPath` in the options to the path of your python executable. See https://github.com/extrabacon/python-shell#pythonshellscript-options-constructor

Maybe I should go back to `python` as default instead of `py` 🤔 Unfortunately python installation on windows has a lot of complicated nuances. Python does this weird thing where it's either installed for a specific user (in which case the user has to opt into adding python to the PATH) or for all users (in which case the `py` executable is created in `C:\\windows`). Neither solution is guaranteed to result in python being in the PATH. Further complicating matters is that windows has a python alias that launches the windows app store to get python if python is not in the PATH. This could either be helpful or a surprising annoyance depending on how you look at it. 

I think to for simplicity and the principle of least surprise I should go back to using `python` as the default python path. Some people might be annoyed at the windows store popping up, but not sure if there's anything I can do about that. Besides mentioning it in the documentation of course. What do you think?

**Comment by LeonardoRick** [comment]
I don't know what's related about the windows store popping up and you setting `python` path as default. I did not had that problem setting python instead of `py`.

I guess it's counter intuitive to have different `pids` when `{ shell: false }`is defined, and `false` is the default value, right? 

If so, yeah, maybe it's better to use python instead

**Comment by Almenon** [comment]
> I don't know what's related about the windows store popping up and you setting python path as default. I did not had this problem setting python instead of py.


see https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor

**Comment by Almenon** [comment]
This should be fixed with pythonshell version 3
