### ISSUE TITLE
Long time two-way communication

### ISSUE THREAD

**Issue by emptist** [extrabacon/python-shell#26]
If I'm right python-shell works for one task per time, with `pysh.end` end the shell and get returned data. Well, is there a way using this for long time communication and finally end the shell by `pysh.send` some special message such as 'shell:end' (binary/text) or `{shell:'end'}` (json mode)?

**Comment by extrabacon** [comment]
Correct, 1 instance = 1 process, which can be long running. You can cleanly end the process by calling `end` (https://github.com/extrabacon/python-shell#endcallback) from your Node app and allow Python to exit normally. You can also forcefully end the process using `#childProcess.kill`.

Using a special message for allowing your Python program to end could be a valid option depending on your needs, but you will need to handle this yourself.

Also, when using long running instances, remember to explicitly flush stdin and stdout (those streams are buffered by the OS). Otherwise you might not receive messages until the buffer has been filled.

**Comment by emptist** [comment]
Thank you for your patient explanation, @extrabacon.
