### ISSUE TITLE
pythonShell with base64 parameters

### ISSUE THREAD

**Issue by killianperea** [extrabacon/python-shell#39]
i'm trying to pass by params 2 base64:

var options = {
        mode: 'json',
        args: [databaseImage, clientImage] // Base64 encode Image
    },
    deferred = new Deferred();
    pythonShell.run('./scripts/matchFace.py', options, function (err, result) {
        if (err) {
            deferred.reject();
        } else {
            deferred.resolve(result[0]);
        }
    });
    return deferred.promise;

But i get this error: spawn ENAMETOOLONG .

My question: pythonShell have a size restriction in the arguments? or it's problem of the node?

Thanks and sorry for my bad english.

**Comment by extrabacon** [comment]
The problem is at the OS level, your command is simply too large. I would strongly suggest using stdin streaming instead of passing string-based arguments. This would allow you to send files of any size with minimal impact on memory. Since python-shell is a thin wrapper on `child_process`, you can use standard Node streaming.

```js
var matchFace = new PythonShell('./scripts/matchFace.py');
// send image data to Python process
matchFace.stdin.write(/* buffer or string */);
// or even better...
myImageStream.pipe(matchFace.stdin);
// then...
matchFace.on('close', function () {
  // done!
});
```

Also, make sure to read the image from stdin in your Python script.
