### ISSUE TITLE
How to pass args to the scripts?

### ISSUE THREAD

**Issue by gbywt** [extrabacon/python-shell#6]
Can I know how to pass the args to the scripts? Is that pass to the python or global variable? Can give an example?

**Comment by extrabacon** [comment]
There is an `args` property you can pass in the options. See https://github.com/extrabacon/python-shell#running-a-python-script-with-arguments-and-options

You specify arguments as an array of strings.

**Comment by gbywt** [comment]
how can I pass the value to the specify args in python ?

**Comment by extrabacon** [comment]
Here's an example from the tests:

echo.py
```python
import sys

# simple argument echo script
for v in sys.argv[1:]:
  print v
```

script.js
```js
PythonShell.run('echo_args.py', {
    args: ['hello', 'world']
}, function (err, results) {
    if (err) return done(err);
    results.should.be.an.Array.and.have.lengthOf(2);
    results.should.eql(['hello', 'world']);
    done();
});
```

**Comment by gbywt** [comment]
how to pass the parameter from python-shell to certain args in python scripts?

example:
python.py

print hi

scripts.js

PythonShell.run('python.py', {
    args: ['hi', 1]
}, function (err) {
if (err){
		throw err;
	}
}

Are this work ?

**Comment by extrabacon** [comment]
I'm sorry, I'm not sure what you are trying to accomplish. Arguments are just an array of strings, nothing more. Your previous example should work.

**Comment by robksawyer** [comment]
I have a question similar to this as well. I'm basically trying to pass the following arguments and I'm having the following issue.

I'm just putting them in an array and passing them along because I'm not sure how to exactly pass them. I tried just as a single element in the array as well. It was a no go.
Arguments:
```
[ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"',
     '-T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame"',
     '-s 1',
     '-e 10',
     'push' ]
```

Issue:
<https://github.com/robksawyer/brenda-web/issues/11>

**Comment by extrabacon** [comment]
@robksawyer: switches and their value are actually 2 parameters. You never have to enclose values in quotes this way.

Instead of:
`['-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"']`
use: 
`['-c', '/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf']`

**Comment by robksawyer** [comment]
Great, thanks. I'll give that a shot.
