### ISSUE TITLE
How to stop the process the which started by PythonShell.run

### ISSUE THREAD

**Issue by praveengithubtest** [extrabacon/python-shell#70]
Hi ,
I am running a python script by using PythonShell.run.But i am unable to stop that .Please help me to stop that particular process.

**Comment by extrabacon** [comment]
If your process runs normally, you should allow it to finish. You cannot forcefully end the process using the `run` method since there is no way to access the underlying child process instance. Instead of using `run`, create an instance. Here is an example: https://github.com/extrabacon/python-shell/issues/45
